apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: !Var nginx_deployment_labels
spec:
  selector:
    matchLabels: !Var nginx_deployment_labels
  template:
    metadata:
      labels: !Var nginx_deployment_labels
    spec:
      enableServiceLinks: false
      containers:
        - name: nginx
          image: nginx:1-alpine
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: Host
                  value: !Lookup static_sites[0]
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: Host
                  value: !Lookup static_sites[0]
            periodSeconds: 30
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx
