apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static
  annotations: !Var ingress_annotations
spec:
  ingressClassName: !Var ingress_class_name
  tls:
    - secretName: ingress-letsencrypt
      hosts: !Var static_sites

  rules: !Loop
    over: !Var static_sites
    as: ingress_public_hostname
    template:
      host: !Var ingress_public_hostname
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nginx
                port:
                  number: 80
