name: cicd

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: qb-arc-runners
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v7
      - uses: azure/setup-helm@v5
      - run: |
          helm upgrade --install static chart \
            --namespace static \
            -f chart/values-production.yaml \
            --wait --timeout 300s
